# Generated by Django 5.0 on 2024-02-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_alter_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='orderid',
            field=models.CharField(default=123, max_length=20),
        ),
    ]
