# Generated by Django 5.0 on 2024-02-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0004_payment_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='orderid',
            field=models.CharField(max_length=20),
        ),
    ]
