# Generated by Django 4.2.6 on 2023-10-13 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_register_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
