# Generated by Django 4.2.6 on 2023-10-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_register_registrationtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='date',
        ),
        migrations.AddField(
            model_name='register',
            name='registrationtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Prefer not to say', 'Prefer not to say'), ('Female', 'Female')], max_length=100),
        ),
    ]
