# Generated by Django 4.2.6 on 2023-10-13 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_register_date_register_registrationtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='registrationtime',
        ),
        migrations.AddField(
            model_name='register',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Prefer not to say', 'Prefer not to say')], max_length=100),
        ),
    ]
