# Generated by Django 5.0 on 2024-02-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_register_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Prefer not to say', 'Prefer not to say'), ('Female', 'Female')], max_length=100),
        ),
    ]
