# Generated by Django 5.0 on 2024-02-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_register_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Prefer not to say', 'Prefer not to say'), ('Male', 'Male')], max_length=100),
        ),
    ]
